name: docker-push

on:
  push:
    branches:
    - master

    tags:
    - v*

env:
  IMAGE_NAME: basic


jobs:
   docker-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo 👀
      uses: actions/checkout@v1

    - name: Log into Dockerhub 🔑
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Building docker image 🚧
      run: "docker build ./container/ --file ./container/Dockerfile -t image"

    - name: Push image 🚀
      run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
         
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
         
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
         
          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

    - name: Logout 👋
      run: "docker logout"