name: relay push base

on:
  push:
    branches:
    - 'master'
    - 'dev/*'

    tags:
    - 'v*'

env:
  IMAGE_NAME: basic
  FPS: base


jobs:
   docker-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo 👀
      uses: actions/checkout@v1

    - name: Log into Dockerhub 🔑
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

    - name: Building docker image 🚧
      run: "docker build ./relay/container/ --file ./relay/container/Dockerfile -t image --build-arg fps=$FPS"

    - name: Push image to Dockerhub 🚀
      run: |
          IMAGE_ID=${{ github.repository }}
          
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
         
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
         
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
         
          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

    - name: Logout 👋
      run: "docker logout"